version: '3.8'

services:
  nginx:
    environment:
      - TLS_MODE=on
    volumes:
      - ${TLS_CERTIFICATE}:/etc/nginx/certs/cert.pem
      - ${TLS_CERTIFICATE_KEY}:/etc/nginx/certs/key.pem


  backend:
    restart: unless-stopped
    volumes:
      - ./backend/:/app/:cached
      - static:/app/static/:delegated
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

  db:
    restart: unless-stopped
    ports:
      - 15239:5432

  redis:
    ports:
      - 6379:6379
