# Generated by Django 4.1.7 on 2023-04-09 23:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(max_length=255, unique=True, verbose_name="Внешний  ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
                ),
                ("role", models.PositiveIntegerField(default=1, verbose_name="Роль")),
                ("auth_type", models.PositiveIntegerField(default=1, verbose_name="Тип")),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(max_length=255, unique=True, verbose_name="Внешний  ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Тип курса",
                "verbose_name_plural": "Типы курса",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(max_length=255, unique=True, verbose_name="Внешний  ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Владелец",
                "verbose_name_plural": "Владельцы",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(max_length=255, unique=True, verbose_name="Внешний  ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата обновления"),
                ),
                ("thumb_url", models.URLField(blank=True, null=True, verbose_name="URL превью")),
                ("cover_url", models.URLField(blank=True, null=True, verbose_name="URL обложки")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последней активности"
                    ),
                ),
                ("total_score", models.FloatField(default=0, verbose_name="Общая оценка")),
                (
                    "total_tasks",
                    models.PositiveIntegerField(default=0, verbose_name="Общее количество задач"),
                ),
                ("unchangeable", models.BooleanField(default=False, verbose_name="Неизменяемо")),
                (
                    "include_weekly_report",
                    models.BooleanField(verbose_name="Включен в еженедельный отчет"),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[(1, "TYPE_1"), (2, "TYPE_2")],
                        max_length=32,
                        verbose_name="Тип контента",
                    ),
                ),
                ("is_netology", models.BooleanField(default=False, verbose_name="Нетология")),
                ("bg_url", models.URLField(blank=True, null=True, verbose_name="URL заставка")),
                ("video_url", models.URLField(blank=True, null=True, verbose_name="URL видео")),
                ("demo", models.BooleanField(default=False, verbose_name="Демо")),
                (
                    "custom_author_names",
                    models.TextField(blank=True, null=True, verbose_name="Имена авторов"),
                ),
                ("custom_contents_link", models.URLField(verbose_name="URL катсомного контента")),
                (
                    "hide_viewer_navigation",
                    models.BooleanField(
                        default=True, verbose_name="Скрыть навигацию для просмотра"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Длительность"),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, null=True, to="courses.author", verbose_name="Авторы"
                    ),
                ),
                (
                    "coursetypes",
                    models.ManyToManyField(
                        blank=True, null=True, to="courses.coursetype", verbose_name="Типы"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.owner",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
