# Generated by Django 4.1.7 on 2023-04-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="coursetypes",
        ),
        migrations.AddField(
            model_name="course",
            name="types",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="types",
                to="courses.coursetype",
                verbose_name="Типы",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="authors",
                to="courses.author",
                verbose_name="Авторы",
            ),
        ),
    ]
